ERROR: 2017-11-09 17:54:44,098: : com.jds.architecture.logging.Log4JLoggerImp: com.jds.architecture.logging.Log4JLoggerImp: error: - Could not read property dbaccess.getconnection.sql.exception from file: dbacess 
java.lang.NullPointerException
	at com.jds.architecture.properties.JDSPropertiesMonitorImp.getProperty(JDSPropertiesMonitorImp.java:132)
	at com.jds.architecture.properties.PropertiesMonitorService.getProperty(PropertiesMonitorService.java:85)
	at com.jds.architecture.service.dbaccess.DBAccessException.getMessage(DBAccessException.java:93)
	at java.base/java.lang.Throwable.getLocalizedMessage(Throwable.java:396)
	at java.base/java.lang.Throwable.toString(Throwable.java:485)
	at java.base/java.lang.String.valueOf(String.java:2801)
	at java.base/java.io.PrintStream.println(PrintStream.java:818)
	at java.base/java.lang.Throwable$WrappedPrintStream.println(Throwable.java:752)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:659)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:648)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:639)
	at test.com.jds.businesscomponent.hr.EmployeeBCTest.setUp(EmployeeBCTest.java:63)
	at junit.framework.TestCase.runBare(TestCase.java:125)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
ERROR: 2017-11-09 17:54:44,105: : com.jds.architecture.logging.Log4JLoggerImp: com.jds.architecture.logging.Log4JLoggerImp: error: - Could not read property dbaccess.getconnection.sql.exception from file: dbacess 
java.lang.NullPointerException
	at com.jds.architecture.properties.JDSPropertiesMonitorImp.getProperty(JDSPropertiesMonitorImp.java:132)
	at com.jds.architecture.properties.PropertiesMonitorService.getProperty(PropertiesMonitorService.java:85)
	at com.jds.architecture.service.dbaccess.DBAccessException.getMessage(DBAccessException.java:93)
	at java.base/java.lang.Throwable.getLocalizedMessage(Throwable.java:396)
	at java.base/java.lang.Throwable.toString(Throwable.java:485)
	at java.base/java.lang.String.valueOf(String.java:2801)
	at java.base/java.io.PrintStream.println(PrintStream.java:818)
	at java.base/java.lang.Throwable$WrappedPrintStream.println(Throwable.java:752)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:659)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:648)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:639)
	at test.com.jds.businesscomponent.hr.EmployeeBCTest.setUp(EmployeeBCTest.java:63)
	at junit.framework.TestCase.runBare(TestCase.java:125)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
ERROR: 2017-11-09 17:54:44,107: : com.jds.architecture.logging.Log4JLoggerImp: com.jds.architecture.logging.Log4JLoggerImp: error: - Could not read property dbaccess.getconnection.sql.exception from file: dbacess 
java.lang.NullPointerException
	at com.jds.architecture.properties.JDSPropertiesMonitorImp.getProperty(JDSPropertiesMonitorImp.java:132)
	at com.jds.architecture.properties.PropertiesMonitorService.getProperty(PropertiesMonitorService.java:85)
	at com.jds.architecture.service.dbaccess.DBAccessException.getMessage(DBAccessException.java:93)
	at java.base/java.lang.Throwable.getLocalizedMessage(Throwable.java:396)
	at java.base/java.lang.Throwable.toString(Throwable.java:485)
	at java.base/java.lang.String.valueOf(String.java:2801)
	at java.base/java.io.PrintStream.println(PrintStream.java:818)
	at java.base/java.lang.Throwable$WrappedPrintStream.println(Throwable.java:752)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:659)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:648)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:639)
	at test.com.jds.businesscomponent.hr.EmployeeBCTest.setUp(EmployeeBCTest.java:63)
	at junit.framework.TestCase.runBare(TestCase.java:125)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
ERROR: 2017-11-09 17:54:44,109: : com.jds.architecture.logging.Log4JLoggerImp: com.jds.architecture.logging.Log4JLoggerImp: error: - Could not read property dbaccess.getconnection.sql.exception from file: dbacess 
java.lang.NullPointerException
	at com.jds.architecture.properties.JDSPropertiesMonitorImp.getProperty(JDSPropertiesMonitorImp.java:132)
	at com.jds.architecture.properties.PropertiesMonitorService.getProperty(PropertiesMonitorService.java:85)
	at com.jds.architecture.service.dbaccess.DBAccessException.getMessage(DBAccessException.java:93)
	at java.base/java.lang.Throwable.getLocalizedMessage(Throwable.java:396)
	at java.base/java.lang.Throwable.toString(Throwable.java:485)
	at java.base/java.lang.String.valueOf(String.java:2801)
	at java.base/java.io.PrintStream.println(PrintStream.java:818)
	at java.base/java.lang.Throwable$WrappedPrintStream.println(Throwable.java:752)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:659)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:648)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:639)
	at test.com.jds.businesscomponent.hr.EmployeeBCTest.setUp(EmployeeBCTest.java:63)
	at junit.framework.TestCase.runBare(TestCase.java:125)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
ERROR: 2017-11-09 17:54:44,113: : com.jds.architecture.logging.Log4JLoggerImp: com.jds.architecture.logging.Log4JLoggerImp: error: - Could not read property dbaccess.getconnection.sql.exception from file: dbacess 
java.lang.NullPointerException
	at com.jds.architecture.properties.JDSPropertiesMonitorImp.getProperty(JDSPropertiesMonitorImp.java:132)
	at com.jds.architecture.properties.PropertiesMonitorService.getProperty(PropertiesMonitorService.java:85)
	at com.jds.architecture.service.dbaccess.DBAccessException.getMessage(DBAccessException.java:93)
	at java.base/java.lang.Throwable.getLocalizedMessage(Throwable.java:396)
	at java.base/java.lang.Throwable.toString(Throwable.java:485)
	at java.base/java.lang.String.valueOf(String.java:2801)
	at java.base/java.io.PrintStream.println(PrintStream.java:818)
	at java.base/java.lang.Throwable$WrappedPrintStream.println(Throwable.java:752)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:659)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:648)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:639)
	at test.com.jds.businesscomponent.hr.EmployeeBCTest.setUp(EmployeeBCTest.java:63)
	at junit.framework.TestCase.runBare(TestCase.java:125)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
ERROR: 2017-11-09 17:54:44,115: : com.jds.architecture.logging.Log4JLoggerImp: com.jds.architecture.logging.Log4JLoggerImp: error: - Could not read property dbaccess.getconnection.sql.exception from file: dbacess 
java.lang.NullPointerException
	at com.jds.architecture.properties.JDSPropertiesMonitorImp.getProperty(JDSPropertiesMonitorImp.java:132)
	at com.jds.architecture.properties.PropertiesMonitorService.getProperty(PropertiesMonitorService.java:85)
	at com.jds.architecture.service.dbaccess.DBAccessException.getMessage(DBAccessException.java:93)
	at java.base/java.lang.Throwable.getLocalizedMessage(Throwable.java:396)
	at java.base/java.lang.Throwable.toString(Throwable.java:485)
	at java.base/java.lang.String.valueOf(String.java:2801)
	at java.base/java.io.PrintStream.println(PrintStream.java:818)
	at java.base/java.lang.Throwable$WrappedPrintStream.println(Throwable.java:752)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:659)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:648)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:639)
	at test.com.jds.businesscomponent.hr.EmployeeBCTest.setUp(EmployeeBCTest.java:63)
	at junit.framework.TestCase.runBare(TestCase.java:125)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
ERROR: 2017-11-09 17:54:44,117: : com.jds.architecture.logging.Log4JLoggerImp: com.jds.architecture.logging.Log4JLoggerImp: error: - Could not read property dbaccess.getconnection.sql.exception from file: dbacess 
java.lang.NullPointerException
	at com.jds.architecture.properties.JDSPropertiesMonitorImp.getProperty(JDSPropertiesMonitorImp.java:132)
	at com.jds.architecture.properties.PropertiesMonitorService.getProperty(PropertiesMonitorService.java:85)
	at com.jds.architecture.service.dbaccess.DBAccessException.getMessage(DBAccessException.java:93)
	at java.base/java.lang.Throwable.getLocalizedMessage(Throwable.java:396)
	at java.base/java.lang.Throwable.toString(Throwable.java:485)
	at java.base/java.lang.String.valueOf(String.java:2801)
	at java.base/java.io.PrintStream.println(PrintStream.java:818)
	at java.base/java.lang.Throwable$WrappedPrintStream.println(Throwable.java:752)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:659)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:648)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:639)
	at test.com.jds.businesscomponent.hr.EmployeeBCTest.setUp(EmployeeBCTest.java:63)
	at junit.framework.TestCase.runBare(TestCase.java:125)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
ERROR: 2017-11-09 17:54:44,118: : com.jds.architecture.logging.Log4JLoggerImp: com.jds.architecture.logging.Log4JLoggerImp: error: - Could not read property dbaccess.getconnection.sql.exception from file: dbacess 
java.lang.NullPointerException
	at com.jds.architecture.properties.JDSPropertiesMonitorImp.getProperty(JDSPropertiesMonitorImp.java:132)
	at com.jds.architecture.properties.PropertiesMonitorService.getProperty(PropertiesMonitorService.java:85)
	at com.jds.architecture.service.dbaccess.DBAccessException.getMessage(DBAccessException.java:93)
	at java.base/java.lang.Throwable.getLocalizedMessage(Throwable.java:396)
	at java.base/java.lang.Throwable.toString(Throwable.java:485)
	at java.base/java.lang.String.valueOf(String.java:2801)
	at java.base/java.io.PrintStream.println(PrintStream.java:818)
	at java.base/java.lang.Throwable$WrappedPrintStream.println(Throwable.java:752)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:659)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:648)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:639)
	at test.com.jds.businesscomponent.hr.EmployeeBCTest.setUp(EmployeeBCTest.java:63)
	at junit.framework.TestCase.runBare(TestCase.java:125)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
ERROR: 2017-11-09 17:54:44,119: : com.jds.architecture.logging.Log4JLoggerImp: com.jds.architecture.logging.Log4JLoggerImp: error: - Could not read property dbaccess.getconnection.sql.exception from file: dbacess 
java.lang.NullPointerException
	at com.jds.architecture.properties.JDSPropertiesMonitorImp.getProperty(JDSPropertiesMonitorImp.java:132)
	at com.jds.architecture.properties.PropertiesMonitorService.getProperty(PropertiesMonitorService.java:85)
	at com.jds.architecture.service.dbaccess.DBAccessException.getMessage(DBAccessException.java:93)
	at java.base/java.lang.Throwable.getLocalizedMessage(Throwable.java:396)
	at java.base/java.lang.Throwable.toString(Throwable.java:485)
	at java.base/java.lang.String.valueOf(String.java:2801)
	at java.base/java.io.PrintStream.println(PrintStream.java:818)
	at java.base/java.lang.Throwable$WrappedPrintStream.println(Throwable.java:752)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:659)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:648)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:639)
	at test.com.jds.businesscomponent.hr.EmployeeBCTest.setUp(EmployeeBCTest.java:63)
	at junit.framework.TestCase.runBare(TestCase.java:125)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
ERROR: 2017-11-09 17:54:44,120: : com.jds.architecture.logging.Log4JLoggerImp: com.jds.architecture.logging.Log4JLoggerImp: error: - Could not read property dbaccess.getconnection.sql.exception from file: dbacess 
java.lang.NullPointerException
	at com.jds.architecture.properties.JDSPropertiesMonitorImp.getProperty(JDSPropertiesMonitorImp.java:132)
	at com.jds.architecture.properties.PropertiesMonitorService.getProperty(PropertiesMonitorService.java:85)
	at com.jds.architecture.service.dbaccess.DBAccessException.getMessage(DBAccessException.java:93)
	at java.base/java.lang.Throwable.getLocalizedMessage(Throwable.java:396)
	at java.base/java.lang.Throwable.toString(Throwable.java:485)
	at java.base/java.lang.String.valueOf(String.java:2801)
	at java.base/java.io.PrintStream.println(PrintStream.java:818)
	at java.base/java.lang.Throwable$WrappedPrintStream.println(Throwable.java:752)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:659)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:648)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:639)
	at test.com.jds.businesscomponent.hr.EmployeeBCTest.setUp(EmployeeBCTest.java:63)
	at junit.framework.TestCase.runBare(TestCase.java:125)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
ERROR: 2017-11-09 17:54:44,121: : com.jds.architecture.logging.Log4JLoggerImp: com.jds.architecture.logging.Log4JLoggerImp: error: - Could not read property dbaccess.getconnection.sql.exception from file: dbacess 
java.lang.NullPointerException
	at com.jds.architecture.properties.JDSPropertiesMonitorImp.getProperty(JDSPropertiesMonitorImp.java:132)
	at com.jds.architecture.properties.PropertiesMonitorService.getProperty(PropertiesMonitorService.java:85)
	at com.jds.architecture.service.dbaccess.DBAccessException.getMessage(DBAccessException.java:93)
	at java.base/java.lang.Throwable.getLocalizedMessage(Throwable.java:396)
	at java.base/java.lang.Throwable.toString(Throwable.java:485)
	at java.base/java.lang.String.valueOf(String.java:2801)
	at java.base/java.io.PrintStream.println(PrintStream.java:818)
	at java.base/java.lang.Throwable$WrappedPrintStream.println(Throwable.java:752)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:659)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:648)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:639)
	at test.com.jds.businesscomponent.hr.EmployeeBCTest.setUp(EmployeeBCTest.java:63)
	at junit.framework.TestCase.runBare(TestCase.java:125)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
ERROR: 2017-11-11 18:53:41,848: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.empdao 
ERROR: 2017-11-11 18:53:42,018: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.empdao 
ERROR: 2017-11-11 18:53:42,054: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.empdao 
ERROR: 2017-11-11 18:53:42,096: : com.jds.architecture.service.dao.DAOException: ?: ?: - sql.create.exception.empdao 
Error : 1, Position : 0, Sql = INSERT INTO employee ( empno, firstname, lastname, middlename, dateofbirth, age, gender, civilstatus, citizenship, sssno, tinno, mobileno, homeno, stadd1, stadd2, city, province, country, educattainment, recognition )VALUES ( :1 , :2 , :3 , :4 , :5 , :6 , :7 , :8 , :9 , :10 , :11 , :12 , :13 , :14 , :15 , :16 ,  :17 , :18  ,:19 ,:20 ) , OriginalSql = INSERT INTO employee ( empno, firstname, lastname, middlename, dateofbirth, age, gender, civilstatus, citizenship, sssno, tinno, mobileno, homeno, stadd1, stadd2, city, province, country, educattainment, recognition )VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,  ?, ? ,?,?) , Error Msg = ORA-00001: unique constraint (HRUSER.EMP_PK) violated

	at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:1145)
	at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:1039)
	at oracle.jdbc.driver.T2CPreparedStatement.executeForDescribe(T2CPreparedStatement.java:733)
	at oracle.jdbc.driver.T2CPreparedStatement.executeForRows(T2CPreparedStatement.java:976)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1119)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3780)
	at oracle.jdbc.driver.OraclePreparedStatement.executeLargeUpdate(OraclePreparedStatement.java:3865)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3845)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1061)
	at com.jds.architecture.service.dao.EmployeeDAO.create(EmployeeDAO.java:38)
	at test.com.jds.architecture.service.dao.EmployeeDAOTest.testCreatePkDuplicated(EmployeeDAOTest.java:121)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
ERROR: 2017-11-11 18:53:42,134: : com.jds.architecture.service.dao.DAOException: ?: ?: - sql.create.exception.empdao 
ERROR: 2017-11-11 18:53:42,175: : com.jds.architecture.service.dao.DAOException: ?: ?: - sql.create.exception.empdao 
Error : 12899, Position : 227, Sql = INSERT INTO employee ( empno, firstname, lastname, middlename, dateofbirth, age, gender, civilstatus, citizenship, sssno, tinno, mobileno, homeno, stadd1, stadd2, city, province, country, educattainment, recognition )VALUES ( :1 , :2 , :3 , :4 , :5 , :6 , :7 , :8 , :9 , :10 , :11 , :12 , :13 , :14 , :15 , :16 ,  :17 , :18  ,:19 ,:20 ) , OriginalSql = INSERT INTO employee ( empno, firstname, lastname, middlename, dateofbirth, age, gender, civilstatus, citizenship, sssno, tinno, mobileno, homeno, stadd1, stadd2, city, province, country, educattainment, recognition )VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,  ?, ? ,?,?) , Error Msg = ORA-12899: value too large for column "HRUSER"."EMPLOYEE"."EMPNO" (actual: 31, maximum: 30)

	at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:1145)
	at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:1039)
	at oracle.jdbc.driver.T2CPreparedStatement.executeForDescribe(T2CPreparedStatement.java:733)
	at oracle.jdbc.driver.T2CPreparedStatement.executeForRows(T2CPreparedStatement.java:976)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1119)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3780)
	at oracle.jdbc.driver.OraclePreparedStatement.executeLargeUpdate(OraclePreparedStatement.java:3865)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3845)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1061)
	at com.jds.architecture.service.dao.EmployeeDAO.create(EmployeeDAO.java:38)
	at test.com.jds.architecture.service.dao.EmployeeDAOTest.testCreateLengthIncorrect(EmployeeDAOTest.java:172)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
ERROR: 2017-11-11 18:53:42,214: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.empdao 
ERROR: 2017-11-11 18:53:42,251: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.empdao 
ERROR: 2017-11-11 18:53:42,288: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.empdao 
ERROR: 2017-11-11 18:53:42,326: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.empdao 
ERROR: 2017-11-11 18:53:42,362: : com.jds.architecture.service.dao.DAOException: ?: ?: - update.exception.empdao 
java.lang.NullPointerException
	at com.jds.architecture.service.dao.EmployeeDAO.update(EmployeeDAO.java:170)
	at test.com.jds.architecture.service.dao.EmployeeDAOTest.testUpdateConnectionNull(EmployeeDAOTest.java:352)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
ERROR: 2017-11-11 18:53:42,400: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.empdao 
ERROR: 2017-11-11 18:53:42,438: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.empdao 
ERROR: 2017-11-11 18:53:42,546: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.empdao 
ERROR: 2017-11-11 18:53:42,625: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.empdao 
ERROR: 2017-11-11 18:53:59,659: : com.jds.architecture.service.dao.DAOException: ?: ?: - create.exception.catdao 
java.lang.NullPointerException
	at com.jds.architecture.service.dao.SkillCategoryDAO.create(SkillCategoryDAO.java:41)
	at test.com.jds.architecture.service.dao.SkillCategoryDAOTest.testCreateConnectionNull(SkillCategoryDAOTest.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
ERROR: 2017-11-11 18:53:59,702: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.catdao 
ERROR: 2017-11-11 18:53:59,863: : com.jds.architecture.service.dao.DAOException: ?: ?: - sql.create.exception.catdao 
Error : 1400, Position : 59, Sql = INSERT INTO skillcategory(id, name, description) VALUES ( :1  , :2  , :3 ), OriginalSql = INSERT INTO skillcategory(id, name, description) VALUES ( ? , ? , ?), Error Msg = ORA-01400: cannot insert NULL into ("HRUSER"."SKILLCATEGORY"."ID")

	at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:1145)
	at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:1039)
	at oracle.jdbc.driver.T2CPreparedStatement.executeForDescribe(T2CPreparedStatement.java:733)
	at oracle.jdbc.driver.T2CPreparedStatement.executeForRows(T2CPreparedStatement.java:976)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1119)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3780)
	at oracle.jdbc.driver.OraclePreparedStatement.executeLargeUpdate(OraclePreparedStatement.java:3865)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3845)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1061)
	at com.jds.architecture.service.dao.SkillCategoryDAO.create(SkillCategoryDAO.java:44)
	at test.com.jds.architecture.service.dao.SkillCategoryDAOTest.testCreateNotNullError(SkillCategoryDAOTest.java:102)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
ERROR: 2017-11-11 18:53:59,902: : com.jds.architecture.service.dao.DAOException: ?: ?: - sql.create.exception.catdao 
Error : 12899, Position : 59, Sql = INSERT INTO skillcategory(id, name, description) VALUES ( :1  , :2  , :3 ), OriginalSql = INSERT INTO skillcategory(id, name, description) VALUES ( ? , ? , ?), Error Msg = ORA-12899: value too large for column "HRUSER"."SKILLCATEGORY"."ID" (actual: 31, maximum: 30)

	at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:1145)
	at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:1039)
	at oracle.jdbc.driver.T2CPreparedStatement.executeForDescribe(T2CPreparedStatement.java:733)
	at oracle.jdbc.driver.T2CPreparedStatement.executeForRows(T2CPreparedStatement.java:976)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1119)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3780)
	at oracle.jdbc.driver.OraclePreparedStatement.executeLargeUpdate(OraclePreparedStatement.java:3865)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3845)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1061)
	at com.jds.architecture.service.dao.SkillCategoryDAO.create(SkillCategoryDAO.java:44)
	at test.com.jds.architecture.service.dao.SkillCategoryDAOTest.testCreateLengthIncorrect(SkillCategoryDAOTest.java:117)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
ERROR: 2017-11-11 18:53:59,938: : com.jds.architecture.service.dao.DAOException: ?: ?: - sql.create.exception.catdao 
Error : 1, Position : 0, Sql = INSERT INTO skillcategory(id, name, description) VALUES ( :1  , :2  , :3 ), OriginalSql = INSERT INTO skillcategory(id, name, description) VALUES ( ? , ? , ?), Error Msg = ORA-00001: unique constraint (HRUSER.SKILLCATEGORY_PK) violated

	at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:1145)
	at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:1039)
	at oracle.jdbc.driver.T2CPreparedStatement.executeForDescribe(T2CPreparedStatement.java:733)
	at oracle.jdbc.driver.T2CPreparedStatement.executeForRows(T2CPreparedStatement.java:976)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1119)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3780)
	at oracle.jdbc.driver.OraclePreparedStatement.executeLargeUpdate(OraclePreparedStatement.java:3865)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3845)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1061)
	at com.jds.architecture.service.dao.SkillCategoryDAO.create(SkillCategoryDAO.java:44)
	at test.com.jds.architecture.service.dao.SkillCategoryDAOTest.testCreatePrimaryKey(SkillCategoryDAOTest.java:129)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
ERROR: 2017-11-11 18:53:59,976: : com.jds.architecture.service.dao.DAOException: ?: ?: - sql.create.exception.catdao 
Error : 1, Position : 0, Sql = INSERT INTO skillcategory(id, name, description) VALUES ( :1  , :2  , :3 ), OriginalSql = INSERT INTO skillcategory(id, name, description) VALUES ( ? , ? , ?), Error Msg = ORA-00001: unique constraint (HRUSER.SKILLCATEGORK_UK) violated

	at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:1145)
	at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:1039)
	at oracle.jdbc.driver.T2CPreparedStatement.executeForDescribe(T2CPreparedStatement.java:733)
	at oracle.jdbc.driver.T2CPreparedStatement.executeForRows(T2CPreparedStatement.java:976)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1119)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3780)
	at oracle.jdbc.driver.OraclePreparedStatement.executeLargeUpdate(OraclePreparedStatement.java:3865)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3845)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1061)
	at com.jds.architecture.service.dao.SkillCategoryDAO.create(SkillCategoryDAO.java:44)
	at test.com.jds.architecture.service.dao.SkillCategoryDAOTest.testCreateUniqueKey(SkillCategoryDAOTest.java:142)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
ERROR: 2017-11-11 18:54:00,011: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.catdao 
ERROR: 2017-11-11 18:54:00,047: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.catdao 
ERROR: 2017-11-11 18:54:00,083: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.catdao 
ERROR: 2017-11-11 18:54:00,120: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.catdao 
ERROR: 2017-11-11 18:54:00,157: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.catdao 
ERROR: 2017-11-11 18:54:00,190: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.catdao 
ERROR: 2017-11-11 18:54:00,227: : com.jds.architecture.service.dao.DAOException: ?: ?: - update.exception.catdao 
java.lang.NullPointerException
	at com.jds.architecture.service.dao.SkillCategoryDAO.update(SkillCategoryDAO.java:173)
	at test.com.jds.architecture.service.dao.SkillCategoryDAOTest.testUpdateConnectionNull(SkillCategoryDAOTest.java:315)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
ERROR: 2017-11-11 18:54:00,262: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.catdao 
ERROR: 2017-11-11 18:54:00,295: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.catdao 
ERROR: 2017-11-11 18:54:00,431: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.catdao 
ERROR: 2017-11-11 18:54:00,598: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.catdao 
ERROR: 2017-11-11 23:37:41,189: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.empdao 
ERROR: 2017-11-11 23:37:45,711: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.empdao 
ERROR: 2017-11-11 23:37:50,237: : com.jds.architecture.service.dao.DAOException: ?: ?: - sql.create.exception.empdao 
Error : 1, Position : 0, Sql = INSERT INTO employee ( empno, firstname, lastname, middlename, dateofbirth, age, gender, civilstatus, citizenship, sssno, tinno, mobileno, homeno, stadd1, stadd2, city, province, country, educattainment, recognition )VALUES ( :1 , :2 , :3 , :4 , :5 , :6 , :7 , :8 , :9 , :10 , :11 , :12 , :13 , :14 , :15 , :16 ,  :17 , :18  ,:19 ,:20 ) , OriginalSql = INSERT INTO employee ( empno, firstname, lastname, middlename, dateofbirth, age, gender, civilstatus, citizenship, sssno, tinno, mobileno, homeno, stadd1, stadd2, city, province, country, educattainment, recognition )VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,  ?, ? ,?,?) , Error Msg = ORA-00001: unique constraint (HRUSER.EMP_PK) violated

	at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:1145)
	at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:1039)
	at oracle.jdbc.driver.T2CPreparedStatement.executeForDescribe(T2CPreparedStatement.java:733)
	at oracle.jdbc.driver.T2CPreparedStatement.executeForRows(T2CPreparedStatement.java:976)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1119)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3780)
	at oracle.jdbc.driver.OraclePreparedStatement.executeLargeUpdate(OraclePreparedStatement.java:3865)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3845)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1061)
	at com.jds.architecture.service.dao.EmployeeDAO.create(EmployeeDAO.java:38)
	at test.com.jds.architecture.service.dao.EmployeeDAOTest.testCreatePkDuplicated(EmployeeDAOTest.java:121)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
ERROR: 2017-11-11 23:37:54,757: : com.jds.architecture.service.dao.DAOException: ?: ?: - sql.create.exception.empdao 
ERROR: 2017-11-11 23:37:59,278: : com.jds.architecture.service.dao.DAOException: ?: ?: - sql.create.exception.empdao 
Error : 12899, Position : 227, Sql = INSERT INTO employee ( empno, firstname, lastname, middlename, dateofbirth, age, gender, civilstatus, citizenship, sssno, tinno, mobileno, homeno, stadd1, stadd2, city, province, country, educattainment, recognition )VALUES ( :1 , :2 , :3 , :4 , :5 , :6 , :7 , :8 , :9 , :10 , :11 , :12 , :13 , :14 , :15 , :16 ,  :17 , :18  ,:19 ,:20 ) , OriginalSql = INSERT INTO employee ( empno, firstname, lastname, middlename, dateofbirth, age, gender, civilstatus, citizenship, sssno, tinno, mobileno, homeno, stadd1, stadd2, city, province, country, educattainment, recognition )VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,  ?, ? ,?,?) , Error Msg = ORA-12899: value too large for column "HRUSER"."EMPLOYEE"."EMPNO" (actual: 31, maximum: 30)

	at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:1145)
	at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:1039)
	at oracle.jdbc.driver.T2CPreparedStatement.executeForDescribe(T2CPreparedStatement.java:733)
	at oracle.jdbc.driver.T2CPreparedStatement.executeForRows(T2CPreparedStatement.java:976)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1119)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3780)
	at oracle.jdbc.driver.OraclePreparedStatement.executeLargeUpdate(OraclePreparedStatement.java:3865)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3845)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1061)
	at com.jds.architecture.service.dao.EmployeeDAO.create(EmployeeDAO.java:38)
	at test.com.jds.architecture.service.dao.EmployeeDAOTest.testCreateLengthIncorrect(EmployeeDAOTest.java:172)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
ERROR: 2017-11-11 23:38:03,795: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.empdao 
ERROR: 2017-11-11 23:38:08,313: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.empdao 
ERROR: 2017-11-11 23:38:12,830: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.empdao 
ERROR: 2017-11-11 23:38:17,353: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.empdao 
ERROR: 2017-11-11 23:38:21,872: : com.jds.architecture.service.dao.DAOException: ?: ?: - update.exception.empdao 
java.lang.NullPointerException
	at com.jds.architecture.service.dao.EmployeeDAO.update(EmployeeDAO.java:170)
	at test.com.jds.architecture.service.dao.EmployeeDAOTest.testUpdateConnectionNull(EmployeeDAOTest.java:352)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
ERROR: 2017-11-11 23:38:26,391: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.empdao 
ERROR: 2017-11-11 23:38:30,908: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.empdao 
ERROR: 2017-11-11 23:38:44,512: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.empdao 
ERROR: 2017-11-11 23:39:07,114: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.empdao 
ERROR: 2017-11-11 23:39:16,149: : com.jds.architecture.service.dao.DAOException: ?: ?: - invalid.object.empdao 
